### ISSUE TITLE
Earth Misspelling

### ISSUE THREAD

**Issue by peterj812** [devinmiller4/Elemental#2]
Earth is misspelt on the "Information on Earth" page. It says Information on EATRH" at the top. EATRH should be changed to EARTH.

**Comment by devinmiller4** [comment]
Oops, I didn't realize that we assign the bugs we find to the other person. Reassigning to myself..

**Comment by devinmiller4** [comment]
Fixed it, see commit https://github.com/devinmiller4/Elemental/commit/9361dcf06aaaf575814997c409a8ef06d4cb9339
