### ISSUE TITLE
Wrong page "Water" link

### ISSUE THREAD

**Issue by devinmiller4** [devinmiller4/Elemental#5]
Clicking the Water link on the elemental list page takes the user to the Earth page instead of the Water page.

**Comment by peterj812** [comment]
Fixed, see commit 27d528e

**Comment by devinmiller4** [comment]
I'm not sure that commit fixed it. It should be good now, see https://github.com/devinmiller4/Elemental/commit/8fee3258444ba38592ae490467db1548494ab961
